// import type은 실행 코드가 아니라 TypeScript의 자료형 검사에만 사용하는 가져오기입니다.
import type {
  CurriculumItem,
  EncouragementMessage,
  GuardianComment,
  LessonMaterial,
  LearningEvent,
  LearningRecord,
  RecommendedCurriculumItem,
  ReportVersion,
  ShareLink,
  Student,
  TeacherNote,
  TrainingSession,
} from './types'

// 서버가 연결되지 않은 UI 목업에서 화면을 채우기 위한 가짜 아동 목록입니다.
// Student[]는 배열의 모든 항목이 Student 설계도를 따라야 한다는 의미입니다.
export const students: Student[] = [
  {
    id: 1,
    name: '김OO',
    age: 10,
    birthDate: '2016-04-12',
    gender: '남자',
    phone: '010-1234-5678',
    school: 'OO초등학교',
    guardianName: '이OO',
    guardianRelation: '어머니',
    guardianPhone: '010-1234-5678',
    guardianEmail: 'ssafy123@ssafy.com',
    address: '서울특별시 강남구 테헤란로 212',
    lastLearningDate: '2026-07-18',
    lastTestDate: '2026-07-14',
    totalLearningTime: '13시간',
    latestTraining: '문장 이해력 향상',
    lastAccess: '오늘 09:20',
    learningStartDate: '2026-07-10',
    weeklyAttendance: '33% (1일/3일)',
  },
  {
    id: 2,
    name: '박OO',
    age: 12,
    birthDate: '2014-11-03',
    gender: '여자',
    phone: '010-9876-5432',
    school: 'OO중학교',
    guardianName: '최OO',
    guardianRelation: '아버지',
    guardianPhone: '010-9876-5432',
    guardianEmail: 'guardian@example.com',
    address: '서울특별시 송파구 올림픽로 120',
    lastLearningDate: '2026-07-17',
    lastTestDate: '2026-07-17',
    totalLearningTime: '33시간',
    latestTraining: '문장 이해력 향상',
    lastAccess: '어제 18:40',
    learningStartDate: '2026-06-21',
    weeklyAttendance: '67% (2일/3일)',
  },
  {
    id: 3,
    name: '이OO',
    age: 8,
    birthDate: '2018-02-21',
    gender: '여자',
    phone: '010-2468-1357',
    school: '새봄초등학교',
    guardianName: '한OO',
    guardianRelation: '어머니',
    guardianPhone: '010-2468-1357',
    guardianEmail: 'saebom.guardian@example.com',
    address: '서울특별시 마포구 월드컵북로 45',
    lastLearningDate: '2026-07-19',
    lastTestDate: '2026-07-12',
    totalLearningTime: '21시간',
    latestTraining: '낱말 유창성 훈련',
    lastAccess: '오늘 08:45',
    learningStartDate: '2026-07-01',
    weeklyAttendance: '100% (3일/3일)',
  },
  {
    id: 4,
    name: '최OO',
    age: 11,
    birthDate: '2015-08-30',
    gender: '남자',
    phone: '010-3579-2468',
    school: '한빛초등학교',
    guardianName: '정OO',
    guardianRelation: '아버지',
    guardianPhone: '010-3579-2468',
    guardianEmail: 'hanbit.guardian@example.com',
    address: '서울특별시 서대문구 연희로 88',
    lastLearningDate: '2026-07-16',
    lastTestDate: '2026-07-10',
    totalLearningTime: '17시간',
    latestTraining: '핵심 내용 찾기',
    lastAccess: '3일 전 17:10',
    learningStartDate: '2026-06-28',
    weeklyAttendance: '33% (1일/3일)',
  },
  {
    id: 5,
    name: '정OO',
    age: 9,
    birthDate: '2017-05-16',
    gender: '여자',
    phone: '010-4680-3579',
    school: '푸른초등학교',
    guardianName: '김OO',
    guardianRelation: '어머니',
    guardianPhone: '010-4680-3579',
    guardianEmail: 'pureun.guardian@example.com',
    address: '서울특별시 성동구 왕십리로 101',
    lastLearningDate: '2026-07-20',
    lastTestDate: '2026-07-18',
    totalLearningTime: '26시간',
    latestTraining: '문장 억양과 끊어 읽기',
    lastAccess: '오늘 10:05',
    learningStartDate: '2026-06-15',
    weeklyAttendance: '67% (2일/3일)',
  },
]

// 여러 화면이 같은 아동을 표시하도록 목록의 첫 아동을 현재 선택 아동으로 사용합니다.
// 끝의 !는 이 위치에는 값이 반드시 있다고 TypeScript에 알려 주는 표시입니다.
export const selectedStudent = students[0]!

function lessonMaterial(
  objective: string,
  teacherGuide: string,
  childInstruction: string,
  items: LessonMaterial['contentItems'],
  duration = 15,
): LessonMaterial {
  return {
    duration,
    objective,
    teacherGuide,
    childInstruction,
    contentItems: items,
    updatedAt: '2026-07-20 18:30',
  }
}

// AI가 학습 행동을 바탕으로 아동마다 서로 다른 순서와 교안 내용을 구성한 목업 데이터입니다.
export const studentCurricula: Record<number, CurriculumItem[]> = {
  1: [
    {
      id: 1,
      studentId: 1,
      category: '음운 인식',
      order: 1,
      title: '첫소리와 끝소리 구분',
      achievement: 92,
      material: lessonMaterial(
        '낱말의 첫소리와 끝소리를 듣고 서로 다른 소리를 구별할 수 있다.',
        '그림을 먼저 보여 준 뒤 낱말을 천천히 읽어 주세요. 정답을 바로 알려주기보다 소리를 한 번 더 들려줍니다.',
        '그림의 이름을 소리 내어 읽고, 처음과 마지막에 들리는 소리를 찾아보세요.',
        [
          {
            id: 1,
            type: 'word',
            label: '첫소리 찾기',
            content: '바나나',
            answer: 'ㅂ',
            hint: '입술을 붙였다 떼며 시작해요.',
          },
          {
            id: 2,
            type: 'word',
            label: '첫소리 찾기',
            content: '딸기',
            answer: 'ㄸ',
            hint: '혀끝에 힘을 주어 시작해요.',
          },
          {
            id: 3,
            type: 'question',
            label: '끝소리 비교',
            content: '수박과 가방의 마지막 소리는 같을까요?',
            answer: '같아요. 둘 다 ㅇ 소리로 끝나요.',
            hint: '두 낱말의 마지막 한 글자만 다시 읽어보세요.',
          },
        ],
      ),
    },
    {
      id: 2,
      studentId: 1,
      category: '음운 인식',
      order: 2,
      title: '음절 분리와 합성',
      achievement: 86,
      material: lessonMaterial(
        '낱말을 음절 단위로 나누고 다시 하나의 낱말로 합칠 수 있다.',
        '손뼉을 치며 음절 수를 표시하고, 아동이 말한 소리를 순서대로 다시 연결하도록 안내합니다.',
        '낱말을 천천히 나누어 말한 뒤 다시 자연스럽게 이어 읽어보세요.',
        [
          {
            id: 1,
            type: 'word',
            label: '두 음절',
            content: '사과',
            answer: '사 / 과',
            hint: '손뼉을 두 번 쳐보세요.',
          },
          {
            id: 2,
            type: 'word',
            label: '세 음절',
            content: '바나나',
            answer: '바 / 나 / 나',
            hint: '입 모양이 바뀔 때마다 나누어보세요.',
          },
          {
            id: 3,
            type: 'question',
            label: '소리 합치기',
            content: '딸 / 기를 이어 말하면 어떤 낱말이 될까요?',
            answer: '딸기',
            hint: '두 소리 사이를 점점 빠르게 읽어보세요.',
          },
        ],
      ),
    },
    {
      id: 3,
      studentId: 1,
      category: '파닉스',
      order: 3,
      title: 'ㄱㄴㄷㄹㅁㅂ 받침 훈련',
      achievement: 100,
      material: lessonMaterial(
        '대표 받침이 포함된 낱말을 정확한 소리로 읽을 수 있다.',
        '받침에서 입 모양이 멈추는 위치를 보여 주고, 낱말과 짧은 문장 순서로 확장합니다.',
        '색으로 표시된 받침에 주의하며 낱말과 문장을 소리 내어 읽어보세요.',
        [
          {
            id: 1,
            type: 'word',
            label: 'ㄱ 받침',
            content: '수박 · 책 · 부엌',
            answer: 'ㄱ 소리',
            hint: '혀의 뒷부분을 입천장에 붙여요.',
          },
          {
            id: 2,
            type: 'word',
            label: 'ㄴ 받침',
            content: '산 · 문 · 우산',
            answer: 'ㄴ 소리',
            hint: '혀끝을 윗잇몸에 붙여요.',
          },
          {
            id: 3,
            type: 'sentence',
            label: '문장 읽기',
            content: '민수는 큰 수박을 한 입 먹었습니다.',
            answer: '끊김 없이 정확하게 읽기',
            hint: '받침 뒤의 다음 소리를 천천히 연결해보세요.',
          },
        ],
      ),
    },
    {
      id: 4,
      studentId: 1,
      category: '파닉스',
      order: 4,
      title: 'ㄲㅆ 받침 훈련',
      achievement: 75,
      material: lessonMaterial(
        '겹받침이 포함된 낱말의 대표 소리를 구별하여 읽을 수 있다.',
        '낱말을 단독으로 읽은 뒤 조사가 붙을 때 소리가 어떻게 달라지는지 비교합니다.',
        '낱말을 읽고, 뒤에 다른 글자가 붙었을 때 달라지는 소리를 확인해보세요.',
        [
          {
            id: 1,
            type: 'word',
            label: 'ㄲ 받침',
            content: '밖 · 부엌',
            answer: 'ㄱ 소리',
            hint: '마지막 소리는 짧게 멈춰요.',
          },
          {
            id: 2,
            type: 'word',
            label: 'ㅆ 받침',
            content: '있다 · 했다',
            answer: 'ㄷ 소리',
            hint: '혀끝을 윗잇몸에 붙이며 끝내요.',
          },
          {
            id: 3,
            type: 'sentence',
            label: '문장 읽기',
            content: '가방이 문 밖에 놓여 있습니다.',
            answer: '밖에를 자연스럽게 이어 읽기',
            hint: '밖과 에를 따로 읽은 뒤 이어보세요.',
          },
        ],
      ),
    },
    {
      id: 5,
      studentId: 1,
      category: '유창성',
      order: 5,
      title: '짧은 문장 유창하게 읽기',
      achievement: 62,
      material: lessonMaterial(
        '짧은 문장을 의미 단위로 끊어 자연스러운 속도로 읽을 수 있다.',
        '첫 번째 읽기에서는 정확도를, 두 번째 읽기에서는 속도와 억양을 확인합니다.',
        '빗금이 있는 곳에서 잠깐 쉬며 두 번 읽어보세요.',
        [
          {
            id: 1,
            type: 'sentence',
            label: '기본 문장',
            content: '노란 나비가 / 꽃밭 위를 / 천천히 날아갑니다.',
            answer: '의미 단위로 세 번 끊어 읽기',
            hint: '빗금에서 짧게 숨을 쉬어요.',
          },
          {
            id: 2,
            type: 'sentence',
            label: '감정 표현',
            content: '와, 커다란 무지개가 떴다!',
            answer: '놀라는 느낌을 살려 읽기',
            hint: '느낌표에서 목소리를 조금 높여요.',
          },
        ],
        12,
      ),
    },
    {
      id: 6,
      studentId: 1,
      category: '유창성',
      order: 6,
      title: '문장 억양과 끊어 읽기',
      achievement: 57,
      material: lessonMaterial(
        '문장 부호와 의미에 맞는 억양을 사용하여 글을 읽을 수 있다.',
        '평서문, 의문문, 감탄문의 끝소리를 비교해 들려주고 아동이 따라 읽게 합니다.',
        '문장 부호를 살펴보고 말하는 사람의 마음이 드러나도록 읽어보세요.',
        [
          {
            id: 1,
            type: 'sentence',
            label: '의문문',
            content: '오늘도 함께 도서관에 갈래?',
            answer: '문장 끝을 자연스럽게 올려 읽기',
            hint: '궁금한 표정을 지으며 읽어보세요.',
          },
          {
            id: 2,
            type: 'sentence',
            label: '감탄문',
            content: '정말 멋진 생각이야!',
            answer: '기쁜 마음을 담아 강조하기',
            hint: '정말과 멋진을 조금 힘주어 읽어요.',
          },
        ],
      ),
    },
    {
      id: 7,
      studentId: 1,
      category: '이해력',
      order: 7,
      title: '핵심 문장 찾기',
      achievement: 48,
      material: lessonMaterial(
        '짧은 글에서 중심 내용을 나타내는 핵심 문장을 찾을 수 있다.',
        '반복해서 등장하는 낱말에 표시하게 하고, 각 문장이 글 전체를 대표하는지 비교합니다.',
        '글을 읽고 가장 중요한 내용을 담은 문장을 골라보세요.',
        [
          {
            id: 1,
            type: 'sentence',
            label: '읽기 자료',
            content:
              '꿀벌은 꽃에서 꿀을 모읍니다. 꽃가루를 옮겨 식물이 열매를 맺도록 돕기도 합니다. 꿀벌은 자연에 꼭 필요한 곤충입니다.',
            answer: '꿀벌은 자연에 꼭 필요한 곤충입니다.',
            hint: '앞의 두 문장을 모두 아우르는 문장을 찾아보세요.',
          },
          {
            id: 2,
            type: 'question',
            label: '확인 질문',
            content: '꿀벌이 자연에 필요한 이유는 무엇인가요?',
            answer: '꽃가루를 옮겨 식물이 열매를 맺도록 돕기 때문입니다.',
            hint: '두 번째 문장을 다시 읽어보세요.',
          },
        ],
        18,
      ),
    },
    {
      id: 8,
      studentId: 1,
      category: '이해력',
      order: 8,
      title: '문맥으로 낱말 뜻 추론',
      achievement: 41,
      material: lessonMaterial(
        '낯선 낱말의 뜻을 앞뒤 문장을 이용해 추론할 수 있다.',
        '정답을 먼저 제시하지 말고 낱말 앞뒤에서 뜻을 짐작하게 하는 표현을 찾게 합니다.',
        '밑줄 친 낱말의 앞뒤 내용을 살펴보며 뜻을 짐작해보세요.',
        [
          {
            id: 1,
            type: 'sentence',
            label: '문맥 읽기',
            content: '비가 갑자기 쏟아지자 사람들은 처마 밑으로 황급히 뛰어갔습니다.',
            answer: '매우 급하게',
            hint: '사람들이 갑자기 비를 피하는 모습을 떠올려보세요.',
          },
          {
            id: 2,
            type: 'question',
            label: '뜻 고르기',
            content: '황급히와 가장 가까운 뜻은 무엇일까요? ① 천천히 ② 급하게 ③ 조용히',
            answer: '② 급하게',
            hint: '비가 갑자기 오면 어떻게 움직일까요?',
          },
        ],
        18,
      ),
    },
  ],
  2: [
    {
      id: 1,
      studentId: 2,
      category: '유창성',
      order: 1,
      title: '긴 문장 의미 단위 읽기',
      achievement: 84,
      material: lessonMaterial(
        '긴 문장을 의미 단위로 구분해 자연스럽게 읽을 수 있다.',
        '아동이 스스로 끊어 읽을 위치를 먼저 표시하도록 합니다.',
        '문장의 뜻이 자연스럽게 이어지도록 쉬어 읽을 곳을 표시해보세요.',
        [
          {
            id: 1,
            type: 'sentence',
            label: '문장 읽기',
            content: '해가 지기 전에 우리는 숲길을 지나 작은 마을에 도착했습니다.',
            answer: '해가 지기 전에 / 우리는 숲길을 지나 / 작은 마을에 도착했습니다.',
            hint: '시간, 행동, 장소를 나누어보세요.',
          },
        ],
      ),
    },
    {
      id: 2,
      studentId: 2,
      category: '이해력',
      order: 2,
      title: '인물의 마음 추론',
      achievement: 71,
      material: lessonMaterial(
        '행동과 대사를 근거로 인물의 마음을 설명할 수 있다.',
        '답을 말할 때 반드시 글 속 근거를 함께 찾게 합니다.',
        '인물의 행동과 말을 살펴보고 어떤 마음인지 설명해보세요.',
        [
          {
            id: 1,
            type: 'question',
            label: '마음 추론',
            content:
              '지우는 선물 상자를 몇 번이나 바라보다가 조심스럽게 리본을 풀었습니다. 지우의 마음은 어땠을까요?',
            answer: '기대되고 설레었을 것입니다.',
            hint: '상자를 여러 번 바라본 행동에 주목하세요.',
          },
        ],
        20,
      ),
    },
    {
      id: 3,
      studentId: 2,
      category: '파닉스',
      order: 3,
      title: '겹받침 문장 적용',
      achievement: 68,
      material: lessonMaterial(
        '겹받침이 포함된 낱말을 문장 안에서 정확하게 읽을 수 있다.',
        '낱말 단독 읽기 후 문장 읽기로 확장합니다.',
        '표시된 낱말에 주의하며 문장을 읽어보세요.',
        [
          {
            id: 1,
            type: 'sentence',
            label: '문장 적용',
            content: '닭이 넓은 들판을 천천히 걸었습니다.',
            answer: '닭, 넓은의 받침을 정확히 읽기',
            hint: '낱말을 먼저 따로 읽어보세요.',
          },
        ],
      ),
    },
  ],
}

// 기존 화면과 다른 목업에서 첫 번째 아동의 목록을 기본값으로 사용할 수 있도록 유지합니다.
export const curriculumItems = studentCurricula[1]!

// 다음 회차 추천 목록도 아동별로 서로 다른 순서와 횟수를 가집니다.
export const recommendedCurricula: Record<number, RecommendedCurriculumItem[]> = {
  1: [
    { id: 1, trainingId: 3, category: '파닉스', title: 'ㄱㄴㄷㄹㅁㅂ 받침 훈련', count: 2 },
    { id: 2, trainingId: 4, category: '파닉스', title: 'ㄲㅆ 받침 훈련', count: 1 },
    { id: 3, trainingId: 5, category: '유창성', title: '짧은 문장 유창하게 읽기', count: 1 },
    { id: 4, trainingId: 7, category: '이해력', title: '핵심 문장 찾기', count: 1 },
  ],
  2: [
    { id: 1, trainingId: 2, category: '이해력', title: '인물의 마음 추론', count: 2 },
    { id: 2, trainingId: 1, category: '유창성', title: '긴 문장 의미 단위 읽기', count: 1 },
  ],
}

export const recommendedCurriculum = recommendedCurricula[1]!

// 훈련 이력 카드에 반복 출력할 세션 목록입니다.
export const trainingSessions: TrainingSession[] = [
  {
    id: 1,
    title: '훈련 1. 받침 소리 구분',
    date: '2026-07-14 15:44',
    achievement: 88,
    curriculum: '파닉스(ㄱㄴㄷㄹㅁㅂ 받침 훈련)',
    summary: '받침이 포함된 낱말 12개 중 10개를 정확하게 읽었습니다.',
  },
  {
    id: 2,
    title: '훈련 2. 짧은 문장 읽기',
    date: '2026-07-14 15:41',
    achievement: 100,
    curriculum: '유창성(짧은 문장 읽기)',
    summary: '문장 속도와 억양이 안정적으로 유지되었습니다.',
  },
  {
    id: 3,
    title: '훈련 3. 핵심 내용 찾기',
    date: '2026-07-14 15:38',
    achievement: 50,
    curriculum: '이해력(핵심 내용 찾기)',
    summary: '핵심어를 찾는 과정에서 교수자의 추가 안내가 필요했습니다.',
  },
]

export const learningRecords: LearningRecord[] = [
  {
    id: 1,
    studentId: 1,
    occurredAt: '2026-07-18 15:44',
    activity: '구름 마을의 비밀 · 받침 소리 구분',
    result: 'completed',
    score: 88,
  },
  {
    id: 2,
    studentId: 1,
    occurredAt: '2026-07-18 15:31',
    activity: '토끼의 우체국 · 짧은 문장 읽기',
    result: 'completed',
    score: 76,
    eventId: 101,
  },
  {
    id: 3,
    studentId: 1,
    occurredAt: '2026-07-16 16:05',
    activity: '바닷속 도서관 · 핵심 내용 찾기',
    result: 'completed',
    score: 64,
    eventId: 102,
  },
  {
    id: 4,
    studentId: 2,
    occurredAt: '2026-07-17 18:20',
    activity: '별빛 캠핑 · 문장 유창하게 읽기',
    result: 'completed',
    score: 91,
  },
]

export const learningEvents: LearningEvent[] = [
  {
    id: 101,
    studentId: 1,
    recordId: 2,
    occurredAt: '2026-07-18 15:34',
    storyTitle: '토끼의 우체국',
    sceneTitle: '편지를 읽어요',
    type: 'speech-recognition-low-confidence',
    retryCount: 2,
    finalSucceeded: true,
    usedSafeFallback: false,
    learningOutcome: 'completed',
    status: 'needs-review',
    issueSegment: '받침이 포함된 짧은 구간',
    recognitionConfidence: 62,
    systemResponse: '속도를 낮춘 문장으로 다시 안내한 뒤 학습을 이어갔습니다.',
  },
  {
    id: 102,
    studentId: 1,
    recordId: 3,
    occurredAt: '2026-07-16 16:12',
    storyTitle: '바닷속 도서관',
    sceneTitle: '다음 장면을 골라요',
    type: 'safety-restriction',
    retryCount: 0,
    finalSucceeded: true,
    usedSafeFallback: true,
    learningOutcome: 'completed',
    status: 'follow-up-needed',
    systemResponse: '중립적인 기본 이야기 분기로 이동해 학습을 마쳤습니다.',
  },
]

export const teacherNotes: TeacherNote[] = [
  {
    id: 201,
    studentId: 1,
    source: 'teacher',
    audience: 'teacher-only',
    status: 'active',
    author: '이OO 선생님',
    text: '글자와 소리의 대응이 빠르게 향상되고 있습니다. 받침이 포함된 문장을 읽을 때 속도가 흔들리는 경향이 있어 반복 연습이 필요합니다.',
    createdAt: '2026-07-18 17:10',
    updatedAt: '2026-07-18 17:10',
  },
]

export const encouragementMessages: EncouragementMessage[] = [
  {
    id: 301,
    studentId: 1,
    source: 'teacher',
    audience: 'child',
    status: 'seen-by-child',
    author: '이OO 선생님',
    originalText: '어려운 받침도 끝까지 읽어 낸 노력이 정말 멋졌어!',
    deliveryText: '어려운 받침도 끝까지 읽어 낸 노력이 정말 멋졌어!',
    deliveryTiming: 'immediate',
    deliveredAt: '2026-07-17 16:42',
    seenAt: '2026-07-17 18:03',
    createdAt: '2026-07-17 16:40',
    updatedAt: '2026-07-17 18:03',
  },
  {
    id: 302,
    studentId: 1,
    source: 'guardian',
    audience: 'child',
    status: 'pending-approval',
    author: '이OO 보호자',
    originalText: '요즘 스스로 책을 펼치는 모습이 대견해. 천천히 해도 괜찮아!',
    deliveryText: '스스로 책을 펼치는 모습이 정말 대견해. 천천히 해도 괜찮아!',
    deliveryTiming: 'next-login',
    createdAt: '2026-07-20 20:14',
    updatedAt: '2026-07-20 20:14',
  },
]

export const guardianComments: GuardianComment[] = [
  {
    id: 401,
    studentId: 1,
    source: 'guardian',
    audience: 'teacher-only',
    status: 'unread',
    author: '이OO 보호자',
    reportVersion: 1,
    text: '집에서도 소리 내어 읽는 시간이 늘었습니다. 다음 단계에서 집에서 도울 방법이 있을까요?',
    createdAt: '2026-07-20 20:09',
    updatedAt: '2026-07-20 20:09',
  },
]

export const reportVersions: ReportVersion[] = [
  {
    id: 601,
    studentId: 1,
    version: 2,
    status: 'published',
    periodStart: '2026-06-15',
    periodEnd: '2026-07-15',
    teacherOpinion:
      '아동은 읽기 정확도와 유창성이 함께 향상되었습니다. 다음 학습에서는 낯선 낱말을 문맥으로 추론하는 활동을 강화할 예정입니다.',
    createdAt: '2026-07-21 14:42',
    updatedAt: '2026-07-21 15:10',
    publishedAt: '2026-07-21 15:10',
  },
  {
    id: 600,
    studentId: 1,
    version: 1,
    status: 'shared',
    periodStart: '2026-05-15',
    periodEnd: '2026-06-14',
    teacherOpinion:
      '아동이 짧은 문장을 끝까지 읽는 힘이 안정되었습니다. 받침이 연속되는 낱말은 속도를 늦춰 반복 연습해 주세요.',
    createdAt: '2026-06-18 10:20',
    updatedAt: '2026-06-18 11:05',
    publishedAt: '2026-06-18 11:05',
  },
]

export const activeShareLink: ShareLink = {
  id: 501,
  reportVersionId: 1,
  status: 'active',
  maskedUrl: 'iread.kr/r/••••••8K2P',
  copyValue: 'https://iread.kr/r/mock-8K2P',
  expiresAt: '2026-08-20',
  createdAt: '2026-07-20 18:30',
  firstViewedAt: '2026-07-20 20:02',
  lastViewedAt: '2026-07-20 20:14',
  guardianAuthentication: 'verified',
  guardianContactHint: '010-****-5678',
}
